### ISSUE TITLE
Taskflow is installed instead of Jet

### ISSUE THREAD

**Issue by yurivict** [XanaduAI/jet#76]
cmake downloads and installs Taskflow and Jet isn't installed.

I already have Taskflow installed, there is no need to install it.

How to use externally installed Taskflow?
Why isn't Jet installed?

**Comment by mlxd** [comment]
Hi @yurivict thanks for getting in touch. Can you give us an example of how you are intending to use Jet, and we should be able to help? Specifically:
* Are you installing via the Python package as `pip install quantum-jet`?
* Are you following the development for non-cmake usage at https://quantum-jet.readthedocs.io/en/stable/dev/guide.html#installation ?
* Are you installing JET using CMake using the guide at https://quantum-jet.readthedocs.io/en/stable/dev/guide.html#example-cmake-project ?

**Comment by mlxd** [comment]
Thanks for the update. Jet is a templated header-only library, so I expect you would like option (2). 
However, we designed Jet to not install into your system directories --- this is by design, as we built this to be encapsulated as a stand-alone project in a given directory with an end-user application, as shown by https://quantum-jet.readthedocs.io/en/stable/dev/guide.html#example-cmake-project

If you would like to enable this system-wide, you can always directly copy Jet's `include` directory to your `/usr/local/include`, which should make it available system wide as:

```bash
git clone https://github.com/XanaduAI/jet
sudo cp -r ./jet/include/* /usr/local/include
```

Assuming Taskflow is also on your header path, you should be able to compiled programs as given in the above guides without the CMake build system we use to fetch the libraries automatically. Let us know if the above helps.
